spring:
  profiles:
    active:
      - dev
---
server:
 port: 9501
eureka:
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
        defaultZone: http://admin:a@eureka1:7001/eureka,http://admin:a@eureka2:7002/eureka,http://admin:a@eureka3:7003/eureka
  instance:
    instance-id: baseservice_zuul-gateway
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2    #设置心跳间隔时间
    lease-expiration-duration-in-seconds: 5  # 租约超时时间间隔
spring:
  profiles: dev
  security:
    user:
      name: admin
      password: a
  application:
    name: microservice-zuul-gateway
---
server:
 port: 9502
eureka:
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
        defaultZone: http://admin:a@eureka1:7001/eureka,http://admin:a@eureka2:7002/eureka,http://admin:a@eureka3:7003/eureka
  instance:
    instance-id: baseservice_zuul-gateway
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2    #设置心跳间隔时间
    lease-expiration-duration-in-seconds: 5  # 租约超时时间间隔
spring:
  profiles: beta
  security:
    user:
      name: admin
      password: a
  application:
    name: microservice-zuul-gateway
