spring:
  profiles:
    active:
      - dev
---
server:
 port: 7003
eureka:
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
        defaultZone: http://admin:a@eureka1:7001/eureka,http://admin:a@eureka2:7002/eureka,http://admin:a@eureka3:7003/eureka
  instance: # eureak实例定义
    hostname: localhost # 定义 Eureka 实例所在的主机名称
spring:
  profiles: dev
  security:
    user:
      name: admin
      password: a
  application:
    name: baseservice_eureka
#监控配置
info:
  app.name: PROVIDER2
  company.name: HillCheung
  build.artifactId:  $project.artifactId$
  build.modelVerison: $project.modelVersion$
  build.javaVersion: $java.version$
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
server:
 port: 7003
eureka:
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
        defaultZone: http://admin:a@eureka1:7001/eureka,http://admin:a@eureka2:7002/eureka,http://admin:a@eureka3:7003/eureka
  instance: # eureak实例定义
    hostname: localhost # 定义 Eureka 实例所在的主机名称
spring:
  profiles: beta
  security:
    user:
      name: admin
      password: a
  application:
    name: microcloud-config-eureka-client
#监控配置
info:
  app.name: PROVIDER2
  company.name: HillCheung
  build.artifactId:  $project.artifactId$
  build.modelVerison: $project.modelVersion$
  build.javaVersion: $java.version$
management:
  endpoints:
    web:
      exposure:
        include: '*'
