spring:
  profiles:
    active:
      - dev
---
server:
 port: 8888
spring:
  profiles: dev
  application:
    name: piclibapi
  security:
    user:
      name: admin
      password: a
      roles:
        - USER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a
    url: jdbc:mysql://localhost:3306/testmis81?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #将_转为驼峰命名
mapper:
  identity: MYSQL   # 标识列用mysql  配置主键自动增长
logging:
  level:
    com.yc: debug
    org.springframework.security: debug
eureka:
  client:
    service-url:
      defaultZone: http://admin:a@localhost:7301/eureka
    register-with-eureka: true
  instance:
    instance-id: microservice-provider-product_1   #实例名
    lease-expiration-duration-in-seconds: 90  #如果现在超过了5s的时间间隔( default: 90 s )
    lease-renewal-interval-in-seconds: 30   #设置心跳的时间间隔( default:30s )
#监控配置
info:
  app.name: PROVIDER
  company.name: HillCheung
  build.artifactId:  $project.artifactId$
  build.modelVerison: $project.modelVersion$
  build.javaVersion: $java.version$
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
server:
 port: 8889
spring:
  profiles: dev1
  application:
    name: piclibapi
  #  security:
  #    user:
   #    name: admin
    #   password: a
    #   roles:
     #   - USER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a
    url: jdbc:mysql://localhost:3306/testmis81?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #将_转为驼峰命名
mapper:
  identity: MYSQL   # 标识列用mysql  配置主键自动增长
logging:
  level:
    com.yc: debug
    org.springframework.security: debug
eureka:
  client:
    service-url:
      defaultZone: http://admin:a@localhost:7301/eureka
  instance:
    instance-id: microservice-provider-product_2   #实例名
    lease-expiration-duration-in-seconds: 90  #如果现在超过了5s的时间间隔( default: 90 s )
    lease-renewal-interval-in-seconds: 30   #设置心跳的时间间隔( default:30s )
#监控配置
info:
  app.name: PROVIDER2
  company.name: HillCheung
  build.artifactId:  $project.artifactId$
  build.modelVerison: $project.modelVersion$
  build.javaVersion: $java.version$
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
server:
 port: 8890
spring:
  profiles: dev2
  application:
    name: piclibapi
  #  security:
  #    user:
   #    name: admin
    #   password: a
    #   roles:
     #   - USER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a
    url: jdbc:mysql://localhost:3306/testmis81?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #将_转为驼峰命名
mapper:
  identity: MYSQL   # 标识列用mysql  配置主键自动增长
logging:
  level:
    com.yc: debug
    org.springframework.security: debug
eureka:
  client:
    service-url:
      defaultZone: http://admin:a@localhost:7301/eureka
  instance:
    instance-id: microservice-provider-product_3   #实例名
    lease-expiration-duration-in-seconds: 90  #如果现在超过了5s的时间间隔( default: 90 s )
    lease-renewal-interval-in-seconds: 30   #设置心跳的时间间隔( default:30s )
#监控配置
info:
  app.name: PROVIDER3
  company.name: HillCheung
  build.artifactId:  $project.artifactId$
  build.modelVerison: $project.modelVersion$
  build.javaVersion: $java.version$
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
